GET http://127.0.0.1:8788/configs



###
POST http://localhost:8788/config
Content-Type: application/json

{
  "namespace": "shi",
  "domain": "matrixboot.com",
  "source": "127.0.0.1",
  "resources": 1
}

###

POST http://localhost:8788/config/excel
Content-Type: multipart/form-data;boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="multipartFile"; filename="config.xlsx"
Content-Type: multipart/form-data

< ./config.xlsx
--WebAppBoundary--

###
PUT http://localhost:8788/config
Content-Type: application/json

{
  "id": 1,
  "namespace": "shishaodong2",
  "domain": "matrixboot.com",
  "source": "11.11.11.11"
}




